{% set version = '0.7.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dplyr
  version: {{ version|replace("-", "_") }}

source:
  fn: dplyr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/dplyr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/dplyr/dplyr_{{ version }}.tar.gz
  sha256: 27b3593c09da5e99c0c4fb19ea826edd2cab619f8aaefd0cfd2a4140a0bd9410

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-assertthat
    - r-base
    - r-bh >=1.58.0_1
    - r-r6
    - r-rcpp >=0.12.6
    - r-bindrcpp
    - r-glue
    - r-magrittr
    - r-pkgconfig
    - r-plogr
    - r-rlang >=0.1
    - r-tibble >=1.3.1
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-bh >=1.58.0_1
    - r-r6
    - r-rcpp >=0.12.6
    - r-bindrcpp
    - r-glue
    - r-magrittr
    - r-pkgconfig
    - r-plogr
    - r-rlang >=0.1
    - r-tibble >=1.3.1
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('dplyr')"  # [not win]
    - "\"%R%\" -e \"library('dplyr')\""  # [win]

about:
  home: https://github.com/hadley/dplyr
  license: MIT
  summary: A fast, consistent tool for working with data frame like objects, both in memory and
    out of memory.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
