travis:
  secure:
    BINSTAR_TOKEN: DB3YtxcbIVaNxH5tvq7WZq8xdoRltYIYLLTPoFUQxlkd3LFshkJpgkcc2I9BZhC6jMVWlnHdvjsr/8GIJtZRGG9AZPCTtp6dOLT7JAdgXFb9nf+7iBL4XRrbVXB63ccG+A9jcZVp2az76Hv9uWsNi8ff6WwF4oFVRD923ov4ZbzsXWJxdv0K2YghcQ4TcvhkV3BzyVDadCtBClgu6hOWsvR7rUSEn+S+z1mhywtXBrvBeJPLzWqbiAEDpDjZntRTy/jPPL0GE5CLozEMZVH80kWjKUJmsKItQgP9ScacGKeG0b6iMDsrcoLc0IyJMryjUIOmQtCCuuVWLq9pPNibL7gI9mz2Cf9kfrfCAlNVvrDG0Qq3aM6WVmq9Dx00WsYB3p92tiVnvRPRAzKqaniDqzmkSx+Ly2bFgN60ratfBa1IADwzD1b6iuUyhqbNrpz9klKS2otwihbJzYD4hD57IsV/FLNwf4LyvwaXod+myAiN1tYR/tW2ADFHUSvTRs66pO2oWjPjfFXkByIxyfMVBAvGLu0fz4cfI9kpGD9bLUQ7UiJ97yP/k8YkVq8eWsSAYvO7Edy+qJFlD5oXsyS1I8BlvYQdU4lAaFZy0tgDuzGmk9oTscPJLhYtoWfls50vVBYmpDWqwcsNSa9/zOBZ+CIDO8y2D+jRYnQpWOhhql0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
