travis:
  secure:
    BINSTAR_TOKEN: Hdx6EPxc4xx05fIpJ53xuLBR455iA4wBZort88k9Vpyw49CYIrm43UFVq6nlrBkZ3JDBz21NP9LGLghgccJLq0H74rtn5fGihuJWH7XzsWjfr/FcVOkdKTbLiQtRlHOWV05zoyeCUzyFa12V/0RG2bjiDMhwc0UAizbty4GNsnh4elQEn5NNHiGaFUZ22GvZacVPaKOQ2sgRrTzRNg+u90ICanURgiY+OEBENWaw9oDXtzlU3xUfEdkTAccBlyEcwjiJqLeeIIsQDzmpsmp+aXgARHBZMHUtxSFP/ptOi7YDVdR5m9WkeSn9rfDrleE90WRC7N31sTdbU76vAE8+ackv66lxaTqPCVo3FHDN6xeXAoa/iw+8nruBMRbNCIhT5xvXyyL3HJBct2RrCfFgdXxym9vv6cuaslAxkS+zTh6RCveA8rywXpgR/q0fJvVgZnC5Njja3Uw1ZNnVC3eKciR3E4498/Me2SEMpo9IMkYg2CAdSSaNOPogA1uS9sU2KDaFxPgO84UTp3XckO+fbrTMdRu3p9dxM/LiCOaOJtbKLkURW+WIZWfeKApBtvdT2pQrRLASOSleD/sRSykV1Wo4qx7vsnNGn/8hFx3iA25u1qjn5xADqNx1kDTpnRnKdUSNa4Cne8OJGYWYgKeORHIJ75o4CwlYYsPlPu3y4fY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
