travis:
  secure:
    BINSTAR_TOKEN: w99/mELTGW0JouDHlk3oVpsMm6r55IE6cQGkP9ijy+rw+7WBtzl4NuegvKOm8BgEuMJdEiobe4+WEK+Ixwk4AeljlFCypb6DOov+/rqfWXemTnPX7bOWcStI1Gq1uCvpPSiM96QzV5USdP17D1KeKczcS5jF9g7+eqKTUePznKUHBCP8jktEPtbGk48b301jDWZ3opMJcl7JE32UiLA54fSau1MruYX9UK0SAmmv4Ji4CWDDJflGP1yCLgezCURoLCJ6AY39nNU0ERZaVnWTQSX9wrO5QxqaDvdIUIUzGZ9eBdps7++pZsxwwC4d3+r6WHvgsPt59bhwtLrFOkRDR2DX9tD4zzqu6qu/q30XgmGhSigC3ZsfrNfmSidnYRxdsofgVvj3EvysUpHVyZ4lvzcV/bTmKZ1AmbPGhdGGHJZ8W0ZIN0gq5o3VkaJNAVPChNDQKfvwsGGgCuTystSgpcjuojLtC/UmrE40PN67P1+7AvPpoppGH0Aj5vA82XB46rHzwCkup27EAKCGJTE4wtdH+JVp4aY/3SZFU4YHn/j+otTU1vgMozJ9P5MS5OvhW/02Z5TGtm1+/sZvx7mAao9FhcQM5FwKRgbMaKkTt6Bsv1jrJtvtQA3kZA/dS0Fpk2hglYADipJrcJ0YkYLasei6ByKHXatrWUy8WdPKwR8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
